### ISSUE TITLE
cli syntax error

### ISSUE THREAD

**Issue by yuddy** [nickw444/nessclient#15]
When i type in ness-cli i get a syntax error.

`Traceback (most recent call last):
  File "/home/yuddy/nessclient/env/bin/ness-cli", line 7, in <module>
    from nessclient.cli.__main__ import cli
  File "/home/yuddy/nessclient/env/lib/python3.5/site-packages/nessclient/__init__.py", line 1, in <module>
    from .client import Client
  File "/home/yuddy/nessclient/env/lib/python3.5/site-packages/nessclient/client.py", line 29
    self._on_event_received: Optional[Callable[[BaseEvent], None]] = None
                           ^
SyntaxError: invalid syntax
`

**Comment by nickw444** [comment]
Hi @yuddy. This library is only compatible with python 3.6 and up. You will need to upgrade your python version in order to use this library and CLI tool. 

At the moment I don’t have any plans to make it work with older versions, but if there’s a pressing requirement then this could be reconsidered.

**Comment by yuddy** [comment]
Thanks Nick. Newbie here

**Comment by yuddy** [comment]
Hi Nick,

I installed 3.6 in my virtualenv ran install and everything and still get this error after running ness-cli

Traceback (most recent call last):
  File "/home/yuddy/ness/bin/ness-cli", line 11, in <module>
    load_entry_point('nessclient==0.9.2', 'console_scripts', 'ness-cli')()
  File "/home/yuddy/ness/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/yuddy/ness/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/home/yuddy/ness/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/home/yuddy/ness/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'nessclient.cli'

**Comment by nickw444** [comment]
Hey @yuddy just got an opportunity to take a look into this. I can reproduce it on my machine. Thanks for coming back with the additional info.

I have worked out the issue and have pushed a fix to fix it.

**Comment by yuddy** [comment]
Sweet thanks Nick. Will keep testing. Have you looked into getting this to work with Home Assistant by any chance?

**Comment by nickw444** [comment]
Awesome. Let me know if you run into any other trouble. I've been pretty busy lately, but intend to finish up the home-assistant PR at some point over the next 2 or 3 weeks:

https://github.com/home-assistant/home-assistant/pull/18463#issuecomment-445522924

**Comment by yuddy** [comment]
Nice Nick, looking forward to it.
